<a href="https://colab.research.google.com/github/salonii1030/Numpy_and_Pandas_Task/blob/main/numpy_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
arr = np.array([[1,2],[4,5]])
s = arr.size
ts = arr.itemsize
print("Memory Size of array: ",(s*ts))

Memory Size of array:  32


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
array = np.zeros(10)
array[4]=1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
array =np.array([1,2,3,4,5])
print(array[::-1])

[5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
m = np.arange(0,9)
shape = (3,3)
print(m.reshape(shape))

[0 1 2] [3 4 5] [6 7 8]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
print(np.random.random((3,3,3)))

[[[0.29810805 0.90058678 0.74594597]
  [0.89712488 0.71074314 0.49808995]
  [0.00506035 0.51394266 0.12669511]]

 [[0.59268034 0.96017559 0.85803484]
  [0.44989338 0.55385953 0.64579314]
  [0.71884109 0.04258161 0.08469799]]

 [[0.48036707 0.63213607 0.39959193]
  [0.33571482 0.61953352 0.00290968]
  [0.44636934 0.95936235 0.70543304]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
arr = np.random.random((10,10))
l,m = arr.min(),arr.max()
print(l,m)

0.0015462989079992884 0.9856122155029219


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
print((np.random.random(30)).mean())

0.5297329988022847


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
ar = np.ones((3,3))
ar[1:-1,1:-1] = 0
print(ar)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
print(np.pad(ar,1))

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
#print(np.diag([1,2,3,4]))
print(np.diag(1+np.arange(4), k = -1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
array = np.zeros((8,8), dtype=int)
array[1::2,::2] = 1
array[::2,1::2] = 1
print(array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
ar = np.array( [ [0,1],[1,0] ] )
print(np.tile(ar,(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x = np.random.random((5,5))
min,max = x.min(),x.max()
print((x-min)/(max-min))

[[0.78177982 0.09134047 0.64231713 0.29355174 0.62254806]
 [0.69090002 0.         0.70219347 0.57725242 0.4960729 ]
 [0.46732579 0.32193306 0.51125317 0.67444798 1.        ]
 [0.96468609 0.75424063 0.16590021 0.32462998 0.55214821]
 [0.86108816 0.96252747 0.84031982 0.64928275 0.71365052]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
RGBA = np.dtype( [("red",np.uint8),("green",np.uint8),("blue",np.uint8),("alpha",np.uint8)] )
ar = np.array( (1,2,3,4),dtype=RGBA )
print(ar["blue"])


3


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
ar1= np.random.random((5,3))
ar2 = np.random.random((3,2))
print(ar1 @ ar2)
np.dot(ar1,ar2)

[[0.19310734 0.32283081]
 [1.03832926 1.14944324]
 [0.25657358 0.36161142]
 [0.48943366 0.50185383]
 [0.18262406 0.40355431]]


array([[0.19310734, 0.32283081],
       [1.03832926, 1.14944324],
       [0.25657358, 0.36161142],
       [0.48943366, 0.50185383],
       [0.18262406, 0.40355431]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
ar = np.arange(10)
ar[(ar>=3)&(ar<=8)]*=(-1)
print(ar)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(5)
# Z**Z
# 2 << Z >> 2
# Z <- Z
# 1j*Z
# Z/1/1
Z<Z>Z

ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [ ]:
np.array(0) // np.array(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [ ]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [3]:
arr = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(arr)), arr))

[-2. -4. -1.  7. -9. -7.  3. -1. -2.  2.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
print(np.intersect1d([9,8,7,6],[1,2,6,7]))

[6 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
np.seterr(all="ignore")
np.errstate(all="ignore")

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64("today", "D")- np.timedelta64(1, "D")
today = np.datetime64("today", "D")
tomorrow = np.datetime64("today", "D")+ np.timedelta64(1, "D")

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
print(np.arange("2016-07","2016-08",dtype = "datetime64[D]") )

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3)*4
B = np.ones(3)*5
C = np.ones(3)*6
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.dot(A,B)

-54.0

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
arr = np.random.random((5))
print(arr-arr%1)
print( np.floor(arr) )
print( np.ceil(arr) )
print( arr.astype(int) )
print( np.trunc(arr) )

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 0 0 0 0]
[0. 0. 0. 0. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
mat = np.zeros((5,5))
mat = mat + np.arange(5)
print(mat)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generator():
  for i in range(10):
    yield i
arr = np.fromiter(generator(),dtype=int,count=-1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
v = np.linspace(0,1,11,endpoint=False)[1:]
print(v)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
v = np.random.random((10))
v.sort()
print(v)

[0.223618   0.43708092 0.55443835 0.55792578 0.56964599 0.58098373
 0.67777744 0.7213546  0.87742083 0.90102741]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
print(np.add.reduce(np.arange(5)))

10


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.random.random((3))
B = np.random.random((3))
eq = np.allclose(A,B)
print(eq)

eql = np.array_equal(A,B)
print(eql)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
a = np.zeros(10)
a.flags.writeable = False
a[0] = 1
print(a)

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
mat = np.random.random((10,2))
x,y = mat[:,0], mat[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
pol = np.c_[r,t]
print(pol)

[[1.04403644 1.05776801]
 [0.91810984 1.15806434]
 [0.62913369 1.10180327]
 [1.26665347 0.7962489 ]
 [0.76410729 1.48753114]
 [1.2615282  0.86607948]
 [0.86477048 1.24826986]
 [0.55965691 1.44268174]
 [0.95021889 0.1835668 ]
 [0.5954028  0.04273844]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
vec = np.random.random((10))
vec[vec.argmax()] = 0
print(vec)

[0.87133386 0.27802443 0.66100049 0.25558907 0.32994585 0.
 0.28274185 0.04093892 0.43352924 0.15392787]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [4]:
arr = np.zeros((5,5), [('x',float),('y',float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(arr)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [5]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
import sys

np.set_printoptions(threshold=sys.maxsize)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
vec = np.random.uniform(0,10,10)
scal = 5
vec_1 = np.abs(arr - 5)
ind = vec_1.argmin()
print(vec[ind])

5.791475357041583


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
arr = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(arr)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
arr = np.random.random((100,2))
X,Y = np.atleast_2d(arr[:,0],arr[:,1])
d = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(d)

[[0.         1.13358448 0.67662955 ... 0.63038404 0.51675802 0.20525536]
 [1.13358448 0.         0.6327587  ... 0.65968187 0.90557266 0.9339367 ]
 [0.67662955 0.6327587  0.         ... 0.04636156 0.77893064 0.48375711]
 ...
 [0.63038404 0.65968187 0.04636156 ... 0.         0.7467183  0.43832806]
 [0.51675802 0.90557266 0.77893064 ... 0.7467183  0.         0.46313667]
 [0.20525536 0.9339367  0.48375711 ... 0.43832806 0.46313667 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
fl_arr = np.arange(10, dtype=np.float32)
arr = fl_arr.astype(np.float32, copy=False)
arr[0] = 2
print(fl_arr)

[2. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
f = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
r = np.genfromtxt(f, delimiter=",", dtype=np.int)
print(r)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
arr = np.arange(4).reshape(2,2)
for index, value in np.ndenumerate(arr):
    print(index, value)
for index in np.ndindex(arr.shape):
    print(index, arr[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
sigma,myu = 1.0,0.0

X,Y  = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X**2+Y**2)
G = np.exp(-(D-myu)**2/(2*sigma**2))
print(G)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 10
p = 3
arr = np.zeros((n,n))
np.put(arr, np.random.choice(range(n*n), p, replace=False),5)
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
r = np.random.rand(5,5)
arr = r - r.mean(axis = 1,keepdims = True)
print(arr)

[[-0.12602422  0.04936612  0.3192117  -0.14469744 -0.09785615]
 [-0.36697832 -0.27368655  0.3894499   0.29522927 -0.04401429]
 [ 0.40294481 -0.24708461 -0.31784178 -0.03744186  0.19942345]
 [-0.36645415 -0.0928809   0.45207885  0.22426973 -0.21701354]
 [ 0.11283443  0.26392693 -0.41685383 -0.38230502  0.4223975 ]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
arr = np.random.randint(0,10,(5,5))
print(arr[(-arr)[:,1].argsort()])
print(arr[:,arr[1,:].argsort()])

[[4 9 3 5 0]
 [4 9 9 8 1]
 [7 3 9 2 7]
 [2 2 8 3 0]
 [9 0 4 1 5]]
[[9 5 3 0 4]
 [0 1 4 5 9]
 [3 2 9 7 7]
 [2 3 8 0 2]
 [9 8 9 1 4]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
arr = np.random.randint(0,10,(5,5))
arr = arr.astype(bool)
print((arr).any(axis = 0))
print(~arr)

[ True  True  True  True  True]
[[False False False False  True]
 [ True False False False False]
 [False False False  True False]
 [False False False False  True]
 [False False False False False]]


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
arr = np.random.uniform(0,1,10)
z = 0.5
m = arr.flat[np.abs(arr - z).argmin()]
print(m)

0.5154072095397374


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
v1 = np.ones(10)
i = np.random.randint(0,len(v1),20)
v1 += np.bincount(i, minlength=len(v1))
print(v1)

#or

# np.add.at(Z, I, 1)
# print(Z)

[5. 5. 2. 3. 4. 4. 1. 1. 1. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[60 46 53 49]
 [70 42 57 41]
 [66 41 57 44]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.64597633 0.39414856 0.49146486 0.54233634 0.55270296 0.50244051
 0.62996255 0.40204008 0.5875604  0.43594673]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.5725133 , 2.05649869, 1.20964015, 1.33838893, 1.65137442])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
arr = np.array([1,2,3,4,5])
z = 3
arr_z = np.zeros(len(arr) + (len(arr)-1)*(z))
arr_z[::z+1] = arr
print(arr_z)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
arr = np.arange(16).reshape(4,4)
arr[[0,1]] = arr[[1,0]]
print(arr)

[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 3, 46) ( 3, 96) ( 6, 13) ( 6, 54) ( 7, 46) ( 7, 82) ( 8, 50) ( 8, 90)
 (10, 13) (10, 76) (13, 54) (13, 76) (14, 82) (14, 99) (16, 29) (16, 41)
 (17, 25) (17, 40) (18, 50) (18, 77) (24, 69) (24, 84) (25, 40) (29, 41)
 (46, 82) (46, 96) (50, 77) (50, 90) (69, 84) (82, 99)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(10)
print(average(Z, n=3))

[1. 2. 3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.73731326,  0.79481813,  0.63170477,  0.05368192,  0.64180765,
        0.84191117,  0.31227124,  0.21581112, -0.59406934, -0.59754272,
       -0.1251728 ,  0.50895152, -0.66360984, -0.19761814,  0.2955673 ,
       -0.5188646 ,  0.63171508,  0.14313649,  0.35186841, -0.86567894,
        0.66427612,  0.04877067,  0.6853051 ,  0.38395166,  0.92638148,
        0.22194766, -0.04907273, -0.33372026, -0.83490887, -0.46811071,
       -0.35151682,  0.55113823,  0.55145905,  0.40870426, -0.42500137,
       -0.03975181,  0.11068682,  0.22356111, -0.77503295, -0.03404439,
       -0.66305502,  0.41773882,  0.07220144, -0.68324692, -0.4095412 ,
       -0.56720347,  0.48696934, -0.40641609,  0.76445242,  0.00486332,
        0.42016948, -0.14762521, -0.57180532,  0.87744211, -0.81414556,
       -0.68643469, -0.03981437,  0.89158955,  0.6540539 ,  0.09553445,
       -0.49262614, -0.61821465, -0.75628827, -0.17772766,  0.29430008,
       -0.79591677, -0.26042059,  0.86642956,  0.57976334, -0.28

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[1.28232841 9.57205561 0.17993522 1.99113418 0.37086069 1.78501839
 0.76112898 2.69191527 1.07649523 6.03930095]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 4.81908094  4.78870682  1.695662    2.69625374  6.38407974  0.49681373
   2.9449199   1.47542934  3.08626312  3.35981693]
 [11.89187258  2.3453751   1.13338902  8.30546423 13.11188807  4.92644063
   0.1979848   0.32827396  0.48661601 10.05930548]
 [ 1.17056254 17.74964897  5.11879911  0.56110219  1.42686805 13.3364583
  14.13599681 10.52381198 14.66420866  9.74397384]
 [ 2.74415267  4.81303032 10.30935971  6.17586214  1.62382052  2.76728366
   3.06818895  6.17443057  2.49204931  4.36168992]
 [ 1.48860979  3.57637142  6.7773689   1.67280999  2.7269504   2.39822736
   1.21059352  3.32083135  0.88180738  5.1143406 ]
 [ 4.74921443 12.4836761   4.5175181   5.6313856   2.92680233  5.50200451
   4.78529615  0.74384579  5.5018928   3.60278348]
 [ 2.92304029 10.65204389  2.31643983  2.68571446  5.00320902  6.65951838
   8.65765795  6.39474028  8.92725187  2.67872492]
 [ 4.73843253  1.19328379  8.09071447  0.34077574  5.65867112  6.66797383
   4.49347395  5.58913389  4.36715608  9.79444396]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[5 1 0 5 8 7 3 3 1 3]
 [1 7 6 9 0 2 4 9 5 6]
 [9 1 3 1 5 5 8 4 3 7]
 [8 7 3 5 5 8 0 7 2 4]
 [9 1 7 4 8 3 5 6 4 6]
 [8 9 9 8 6 9 8 0 5 8]
 [1 7 3 3 5 7 4 0 4 7]
 [2 9 2 6 9 1 9 2 4 7]
 [5 9 1 8 8 6 0 0 4 0]
 [6 8 6 2 1 2 5 4 6 1]]
[[0 0 0 0 0]
 [0 5 1 0 5]
 [0 1 7 6 9]
 [0 9 1 3 1]
 [0 8 7 3 5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
arr = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(arr,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
arr = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(arr)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
arr = np.random.randint(0,10,20)
print(np.bincount(arr).argmax())

9


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
arr = np.random.randint(1,5,(10,10))
n = 3
i = 1 + (arr.shape[0]-3)
j = 1 + (arr.shape[1]-3)
C = stride_tricks.as_strided(arr, shape=(i, j, n, n), strides=arr.strides + arr.strides)
print(C)

[[[[1 2 3]
   [2 2 4]
   [4 1 2]]

  [[2 3 1]
   [2 4 4]
   [1 2 4]]

  [[3 1 2]
   [4 4 4]
   [2 4 2]]

  [[1 2 2]
   [4 4 2]
   [4 2 1]]

  [[2 2 4]
   [4 2 2]
   [2 1 4]]

  [[2 4 3]
   [2 2 4]
   [1 4 3]]

  [[4 3 3]
   [2 4 1]
   [4 3 4]]

  [[3 3 2]
   [4 1 2]
   [3 4 2]]]


 [[[2 2 4]
   [4 1 2]
   [3 1 1]]

  [[2 4 4]
   [1 2 4]
   [1 1 2]]

  [[4 4 4]
   [2 4 2]
   [1 2 2]]

  [[4 4 2]
   [4 2 1]
   [2 2 2]]

  [[4 2 2]
   [2 1 4]
   [2 2 4]]

  [[2 2 4]
   [1 4 3]
   [2 4 1]]

  [[2 4 1]
   [4 3 4]
   [4 1 2]]

  [[4 1 2]
   [3 4 2]
   [1 2 3]]]


 [[[4 1 2]
   [3 1 1]
   [2 1 4]]

  [[1 2 4]
   [1 1 2]
   [1 4 4]]

  [[2 4 2]
   [1 2 2]
   [4 4 1]]

  [[4 2 1]
   [2 2 2]
   [4 1 1]]

  [[2 1 4]
   [2 2 4]
   [1 1 4]]

  [[1 4 3]
   [2 4 1]
   [1 4 4]]

  [[4 3 4]
   [4 1 2]
   [4 4 3]]

  [[3 4 2]
   [1 2 3]
   [4 3 1]]]


 [[[3 1 1]
   [2 1 4]
   [1 4 4]]

  [[1 1 2]
   [1 4 4]
   [4 4 4]]

  [[1 2 2]
   [4 4 1]
   [4 4 1]]

  [[2 2 2]
   [4 1 1]
   [4 1 2]]

  [[2 2 4]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 8 14 11 11  9]
 [14  8  2 10 10]
 [11  2  8 42  6]
 [11 10 42  4  9]
 [ 9 10  6  9  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
arr = np.arange(500)
np.random.shuffle(arr)
n = 3
print (arr[np.argsort(arr)[-n:]])
#print (arr[np.argpartition(-arr,n)[:n]])


[497 498 499]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cart_prod(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cart_prod(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
arr = np.array([("GUVI", 5.5, 1),
              ("geek", 9.7, 2)])
final = np.core.records.fromarrays(arr.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(final)

[(b'GUVI', 5.5, 1) (b'geek', 9.7, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
Z = np.random.rand(int(5e7))

%timeit np.power(Z,3)
%timeit Z*Z*Z
%timeit np.einsum('i,i,i->i',Z,Z,Z)

2.72 s ± 187 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
80.4 ms ± 748 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
70.9 ms ± 241 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[2 3 4]
 [0 3 0]
 [1 2 3]
 [1 4 3]
 [1 1 0]
 [3 2 1]
 [2 2 4]
 [1 0 0]
 [0 1 4]
 [4 1 0]]
[[2 3 4]
 [0 3 0]
 [1 2 3]
 [1 4 3]
 [1 1 0]
 [3 2 1]
 [2 2 4]
 [1 0 0]
 [0 1 4]
 [4 1 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
v = np.array([0, 3, 2, 7, 40, 13, 23, 44, 159], dtype=np.uint8)
print(np.unpackbits(v[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 1 1]
 [0 0 1 0 1 0 0 0]
 [0 0 0 0 1 1 0 1]
 [0 0 0 1 0 1 1 1]
 [0 0 1 0 1 1 0 0]
 [1 0 0 1 1 1 1 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,5)
B = np.random.uniform(0,1,5)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[0.15263963, 0.38954345, 0.29453645, 0.09916955, 0.36170943],
       [0.1001398 , 0.25556143, 0.19323174, 0.06506056, 0.23730082],
       [0.12225013, 0.31198803, 0.23589627, 0.07942558, 0.28969557],
       [0.21940323, 0.55992724, 0.4233648 , 0.14254568, 0.5199188 ],
       [0.09521231, 0.24298625, 0.18372355, 0.06185918, 0.22562417]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)               
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.07214378  0.33982531]
